# Generated by Django 5.2 on 2025-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='image',
            field=models.ImageField(upload_to='card_images/'),
        ),
    ]
